---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visiorganize
spec:
  selector:
    matchLabels:
      app: visiorganize
  template:
    metadata:
      labels:
        app: visiorganize
    spec:
      containers:
      - name: visiorganize-app
        image: ghcr.io/aelithron/visiorganize:v1.0.0
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "768Mi"
            cpu: "750m"
        env:
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: visiorganize-secrets
              key: auth-secret
        - name: NEXTAUTH_URL
          value: "http://visiorganize:3000/api/auth"
        - name: AUTH_GITHUB_ID
          value: "placeholder"
          valueFrom:
            secretKeyRef:
              name: visiorganize-secrets
              key: auth-github-secret
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: visiorganize-secrets
              key: mongodb-uri
        - name: MONGODB_DB
          value: "placeholder"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: visiorganize
spec:
  selector:
    app: visiorganize
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: visiorganize-secrets
type: Opaque
data:
  auth-secret: cGxhY2Vob2xkZXI= # placeholder
  auth-github-secret: cGxhY2Vob2xkZXI= # placeholder
  mongodb-uri: cGxhY2Vob2xkZXI= # placeholder
---